---------------------------------------------

SELECT * FROM NOTA_FISCAL.CONTRIBUINTE;
SELECT * FROM NOTA_FISCAL.CONTRIBUINTE c WHERE C.CD_CONTRIBUINTE = '270000039'
SELECT * FROM NOTA_FISCAL.CONTRIBUINTE c ORDER BY c.CNPJ_CONTRIBUINTE ASC, c.NM_FANTASIA DESC;


SELECT * FROM NOTA_FISCAL.DANFE;
SELECT * FROM NOTA_FISCAL.DANFE d 
WHERE d.DATA_EMISSAO BETWEEN TO_DATE('2025-10-31 00:00:00', 'yyyy-mm-dd hh24:mi:ss') AND TO_DATE('2025-10-31 23:59:59', 'yyyy-mm-dd hh24:mi:ss')
ORDER BY d.DATA_EMISSAO DESC, d.VALOR_TOTAL ASC;


SELECT * FROM NOTA_FISCAL.ENDERECO;

/*
SELECT c.CD_CONTRIBUINTE, c.CNPJ_CONTRIBUINTE, c.NM_FANTASIA, 
       d.NUMERO, TO_CHAR(d.DATA_EMISSAO, 'dd/mm/yyyy') DATA_EMISSAO, d.VALOR_TOTAL,
       e.LOGRADOURO, e.MUNICIPIO, e.UF
FROM NOTA_FISCAL.CONTRIBUINTE c
JOIN NOTA_FISCAL.DANFE d ON d.CD_CONTRIBUINTE = c.CD_CONTRIBUINTE
JOIN NOTA_FISCAL.ENDERECO e ON e.CD_CONTRIBUINTE = c.CD_CONTRIBUINTE
AND c.NM_FANTASIA LIKE '%SUPERMERCADO%'
ORDER BY c.NM_FANTASIA, d.DATA_EMISSAO, d.VALOR_TOTAL
OFFSET 10 ROWS 
FETCH NEXT 3 ROWS ONLY
*/

/*
DELETE FROM NOTA_FISCAL.CONTRIBUINTE c WHERE c.CD_CONTRIBUINTE = '270000030';
DELETE FROM NOTA_FISCAL.ENDERECO e WHERE e.CD_CONTRIBUINTE = '270000030';

ALTER USER NOTA_FISCAL QUOTA UNLIMITED ON USERS;

DROP TABLE NOTA_FISCAL.ENDERECO;
DROP TABLE NOTA_FISCAL.DANFE;
DROP TABLE NOTA_FISCAL.CONTRIBUINTE;
*/
---------------------------------------------
